# Generated by Django 3.2.3 on 2021-05-21 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testmodel',
            name='active',
            field=models.NullBooleanField(),
        ),
    ]
