# Generated by Django 3.2.3 on 2021-05-22 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0004_testmodel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testmodel',
            name='active',
            field=models.BooleanField(null=True),
        ),
    ]
