# Generated by Django 3.2.3 on 2021-05-22 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', 'alter_testmodel_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testmodel',
            name='age',
            field=models.PositiveIntegerField(default=50),
        ),
    ]
